[book]
title = "Nix в пилюлях"
authors = ["Luca Bruno"]
description = "Nix в пилюлях --- классическое введение в Nix и NixOS."
language = "ru"
multilingual = false
src = "src"

[output.html]
no-section-label = true
theme = "theme"
curly-quotes = true
